services:
  zookeeper:
    hostname: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
       - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: confluentinc/cp-server:6.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - ./shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://0.0.0.0:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  nifi:
    image: apache/nifi:1.12.1
    hostname: nifi
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
    environment:
       NIFI_WEB_HTTP_PORT: 8080
       NIFI_CLUSTER_IS_NODE: 'true'
       NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
       NIFI_ZK_CONNECT_STRING: "zookeeper:2181"
       NIFI_ELECTION_MAX_WAIT: "1 min"
       NIFI_ZK_ROOT_NODE: "/nifi"

  producer:
    build: ./producer
    depends_on:
      - zookeeper
    environment:
      API_COVID: "https://api.covid19api.com/summary"
      TOPIC: kafka-nifi-src
      BOOTSTRAP_SERVER: "kafka:9092"

  consumer:
    build: ./consumer
    depends_on:
      - zookeeper
    environment:
      TOPIC: kafka-nifi-dst
      BOOTSTRAP_SERVER: "kafka:9092"
